# #07: Menghapus (drop) missing values `(NaN)`
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
## DEPRICATED ##
# df = pd.util.testing.makeMissingDataframe().reset_index() 
# df.head()

In [3]:
n_rows = 30
n_cols = 4
cols = ['A', 'B', 'C', 'D']

df = pd.DataFrame(np.random.randn(n_rows, n_cols), columns=cols)

nan_mask = np.random.rand(n_rows, n_cols) < 0.2
df[nan_mask] = np.nan

df = df.reset_index()
df.head()

   index         A         B         C         D
0      0  0.516076  0.079116 -0.202817  1.058222
1      1       NaN -0.721026 -0.111947 -1.342626
2      2       NaN  0.349353 -1.664095 -0.019539
3      3 -0.254767  0.830741 -1.264514 -1.352101
4      4  0.755976  1.209761  1.332054       NaN

In [4]:
df = df.rename(columns={'index':'Z'})
df.head()

   Z         A         B         C         D
0  0  0.516076  0.079116 -0.202817  1.058222
1  1       NaN -0.721026 -0.111947 -1.342626
2  2       NaN  0.349353 -1.664095 -0.019539
3  3 -0.254767  0.830741 -1.264514 -1.352101
4  4  0.755976  1.209761  1.332054       NaN

In [5]:
df_backup = df.copy(deep=True)

## Menghapus (drop) setiap kolom yang mengandung missing values

In [6]:
df = df.dropna(axis='columns') 
df.head()

   Z
0  0
1  1
2  2
3  3
4  4

## Menghapus (drop) setiap baris yang mengandung missing values

In [7]:
df = df_backup.copy(deep=True)
df = df.dropna(axis='rows')
df.head()

     Z         A         B         C         D
0    0  0.516076  0.079116 -0.202817  1.058222
3    3 -0.254767  0.830741 -1.264514 -1.352101
9    9  0.129913 -0.310577  0.598951 -0.608485
11  11 -0.438096  0.541933 -0.274625  0.887635
12  12  0.403773 -2.308836  0.272621 -0.554832

## Persentase missing values untuk tiap kolom

In [8]:
df = df_backup.copy(deep=True)
df.isna().mean()

Z    0.000000
A    0.166667
B    0.166667
C    0.100000
D    0.200000
dtype: float64

## Menghapus (drop) setiap kolom yang mengandung missing values berdasarkan threshold

In [9]:
treshold = len(df) * 0.9
df = df.dropna(thresh=treshold, axis='columns')
df.head()

   Z         C
0  0 -0.202817
1  1 -0.111947
2  2 -1.664095
3  3 -1.264514
4  4  1.332054