# #46: Seleksi weekdays dan weekends pada data deret waktu (time series)
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
## DEPRECATED #
# n_rows = 365
# n_cols = 2
# cols = ['col1', 'col2']

# df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
#                   columns=cols)

# df.index = pd.util.testing.makeDateIndex(n_rows, freq='D')
# df

In [3]:
n_rows = 365
n_cols = 2
cols = ['col1', 'col2']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')

print(df)

            col1  col2
2024-01-01    11     5
2024-01-02     3    15
2024-01-03    18    18
2024-01-04    19     1
2024-01-05     2     9
...          ...   ...
2024-12-26    11     6
2024-12-27    15     4
2024-12-28    14     6
2024-12-29     3    14
2024-12-30    18    16

[365 rows x 2 columns]

## Seleksi weekdays dan weekends

In [4]:
weekdays_df = df[df.index.dayofweek.isin([0, 1, 2, 3, 4])]
weekdays_df.head(7)

            col1  col2
2024-01-01    11     5
2024-01-02     3    15
2024-01-03    18    18
2024-01-04    19     1
2024-01-05     2     9
2024-01-08    17     2
2024-01-09     2    12

In [5]:
weekends_df = df[df.index.dayofweek.isin([5, 6])]
weekends_df.head(7)

            col1  col2
2024-01-06     5     7
2024-01-07     2     8
2024-01-13     4     8
2024-01-14     9    14
2024-01-20     8     6
2024-01-21    17    12
2024-01-27     6     4