# #36: Menyatukan kolom dengan `str.cat()`
## Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3

## Persiapan Data Frame

In [2]:
data = {'nama': ['bayu', 'indra', 'devi', 'agni'],
        'jenis_kelamin': ['L', 'L', 'P', 'L'], 
        'usia': [23, 21, 22, 25]}

df = pd.DataFrame(data)
df

    nama jenis_kelamin  usia
0   bayu             L    23
1  indra             L    21
2   devi             P    22
3   agni             L    25

## Menyatukan kolom dengan `str.cat()`

In [3]:
df['nama'].str.cat(df['jenis_kelamin'], sep=', ').to_frame()

       nama
0   bayu, L
1  indra, L
2   devi, P
3   agni, L

In [4]:
df['nama_jk'] = df['nama'].str.cat(df['jenis_kelamin'], sep=', ')
df

    nama jenis_kelamin  usia   nama_jk
0   bayu             L    23   bayu, L
1  indra             L    21  indra, L
2   devi             P    22   devi, P
3   agni             L    25   agni, L

In [5]:
df['nama'].str.cat(df['usia'].astype('str'), sep=' - ').to_frame()

         nama
0   bayu - 23
1  indra - 21
2   devi - 22
3   agni - 25

In [6]:
df['nama_usia'] = df['nama'].str.cat(df['usia'].astype('str'), sep=' - ')
df

    nama jenis_kelamin  usia   nama_jk   nama_usia
0   bayu             L    23   bayu, L   bayu - 23
1  indra             L    21  indra, L  indra - 21
2   devi             P    22   devi, P   devi - 22
3   agni             L    25   agni, L   agni - 25