# #08: Memeriksa kesamaan antar dua buah kolom (Series) pada Data Frame
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
data = {'A':[15, 15, 18, np.nan, 12], 
        'B':[15, 15, 18, np.nan, 12]}

df = pd.DataFrame(data)
df

      A     B
0  15.0  15.0
1  15.0  15.0
2  18.0  18.0
3   NaN   NaN
4  12.0  12.0

## Mengenal Pandas Series

In [3]:
df['A']

0    15.0
1    15.0
2    18.0
3     NaN
4    12.0
Name: A, dtype: float64

In [4]:
type(df['A'])

pandas.core.series.Series

In [5]:
type(df)

pandas.core.frame.DataFrame

## Memeriksa kesamaan dengan operator `==`

In [6]:
df['A'] == df['B']

0     True
1     True
2     True
3    False
4     True
dtype: bool

## Memeriksa kesamaan dengan method `equals()`

In [7]:
df['A'].equals(df['B'])

True

## Memeriksa kesamaan antar dua Data Frame

In [8]:
df1 = df.copy(deep=True)

df.equals(df1)

True

In [9]:
df == df1

       A      B
0   True   True
1   True   True
2   True   True
3  False  False
4   True   True