# #13: Konversi nilai numerik ke dalam sejumlah kategori
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 10
n_cols = 1
cols = ('usia',)

df = pd.DataFrame(np.random.randint(1, 99, size=(n_rows, n_cols)), 
                  columns=cols)
df

   usia
0    44
1    59
2    61
3    28
4    43
5    75
6    52
7    61
8    18
9    92

## Pengelompokkan nilai numerik ke dalam beberapa kategori menggunakan `cut()`

In [3]:
df['kelompok_usia'] = pd.cut(df['usia'], 
                             bins=[0, 18, 65, 99], 
                             labels=['anak', 'dewasa', 'manula'])
df

   usia kelompok_usia
0    44        dewasa
1    59        dewasa
2    61        dewasa
3    28        dewasa
4    43        dewasa
5    75        manula
6    52        dewasa
7    61        dewasa
8    18          anak
9    92        manula