# #54: Menyimpan Data Frame sebagai File `CSV`
## Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3

## Persiapan Data Frame

In [2]:
data = {'nama': ['bayu', 'indra', 'devi', 'agni'], 
        'jenis_kelamin': ['L', 'L', 'P', 'L'],
        'usia': [23, 21, 22, 25]}

df = pd.DataFrame(data)
df

    nama jenis_kelamin  usia
0   bayu             L    23
1  indra             L    21
2   devi             P    22
3   agni             L    25

## Menyimpan Data Frame sebagai File `CSV`

In [3]:
df.to_csv('data_peserta.csv')

In [4]:
df = pd.read_csv('data_peserta.csv')
# df = pd.read_csv('data_peserta.csv', index_col=0)

df

   Unnamed: 0   nama jenis_kelamin  usia
0           0   bayu             L    23
1           1  indra             L    21
2           2   devi             P    22
3           3   agni             L    25

In [5]:
# df = pd.read_csv('data_peserta.csv')
df = pd.read_csv('data_peserta.csv', index_col=0)

df

    nama jenis_kelamin  usia
0   bayu             L    23
1  indra             L    21
2   devi             P    22
3   agni             L    25

In [6]:
df.to_csv('data_peserta.csv', index=False)
df = pd.read_csv('data_peserta.csv')
df

    nama jenis_kelamin  usia
0   bayu             L    23
1  indra             L    21
2   devi             P    22
3   agni             L    25