# #09: Membagi Data Frame menjadi dua secara acak
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0   7   1   3   1   3
1  19  10   2   2  15
2  14  13  13  16   8
3   1   5  10  11   2
4  13   1  11  12   4
5   7  16  15  10   4
6   7   9  17  12  11
7   3  18  11  10  13
8   3   8  17  16   3
9   8   3   9   9  19

## Membagi Data Frame menjadi dua secara acak berdasarkan proporsi tertentu

In [3]:
df.shape

(10, 5)

In [4]:
proporsi = 0.7
df_1 = df.sample(frac=proporsi)
df_2 = df.drop(df_1.index)

print(f'df_1 shape: {df_1.shape}')
print(f'df_2 shape: {df_2.shape}')

df_1 shape: (7, 5)
df_2 shape: (3, 5)

In [5]:
df_1

    A   B   C   D   E
7   3  18  11  10  13
6   7   9  17  12  11
1  19  10   2   2  15
9   8   3   9   9  19
5   7  16  15  10   4
4  13   1  11  12   4
8   3   8  17  16   3

In [6]:
df_2

    A   B   C   D  E
0   7   1   3   1  3
2  14  13  13  16  8
3   1   5  10  11  2