# #56: Mengeluarkan kolom dari Data Frame
## Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3

## Persiapan Data Frame

In [2]:
data = {'nama': ['bayu', 'indra', 'devi', 'agni'], 
        'jenis_kelamin': ['L', 'L', 'P', 'L'],
        'usia': [23, 21, 22, 25]}

df = pd.DataFrame(data)
df

    nama jenis_kelamin  usia
0   bayu             L    23
1  indra             L    21
2   devi             P    22
3   agni             L    25

## Mengeluarkan kolom dari Data Frame

In [3]:
usia = df.pop('usia').to_frame()

In [4]:
df

    nama jenis_kelamin
0   bayu             L
1  indra             L
2   devi             P
3   agni             L

In [5]:
usia

   usia
0    23
1    21
2    22
3    25