# #43: Menangani whitespace pada Data Frame
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
data = {'nim': ['10', '11', '12', '13', '  '],
        'nama': ['adi', '  ', 'tejo', '  ', 'bejo']}

df = pd.DataFrame(data)
df

  nim  nama
0  10   adi
1  11
2  12  tejo
3  13
4      bejo

## Menangani whitespace pada Data Frame

In [3]:
df

  nim  nama
0  10   adi
1  11
2  12  tejo
3  13
4      bejo

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nim     5 non-null      object
 1   nama    5 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

In [5]:
df = df.replace(r'^\s*$', np.nan, regex=True)
df

   nim  nama
0   10   adi
1   11   NaN
2   12  tejo
3   13   NaN
4  NaN  bejo

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nim     4 non-null      object
 1   nama    3 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes