# #04: Pemilihan kolom (columns selection) pada Data Frame berdasarkan tipe data
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 5
n_cols = 2
cols = ['bil_pecahan', 'bil_bulat']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)

df['bil_pecahan'] = df['bil_pecahan'].astype('float')

df

   bil_pecahan  bil_bulat
0          7.0         14
1         11.0         14
2         19.0          7
3         10.0          7
4         17.0          6

In [3]:
# df.index = pd.util.testing.makeDateIndex(n_rows, freq='H')
df.index = pd.date_range(start='2023-10-01', periods=n_rows, freq='H')

df = df.reset_index()

df['teks'] = list('ABCDE')

df

                index  bil_pecahan  bil_bulat teks
0 2023-10-01 00:00:00          7.0         14    A
1 2023-10-01 01:00:00         11.0         14    B
2 2023-10-01 02:00:00         19.0          7    C
3 2023-10-01 03:00:00         10.0          7    D
4 2023-10-01 04:00:00         17.0          6    E

In [4]:
df.dtypes

index          datetime64[ns]
bil_pecahan           float64
bil_bulat               int64
teks                   object
dtype: object

## Memilih kolom bertipe data numerik

In [5]:
df.select_dtypes(include='number')

   bil_pecahan  bil_bulat
0          7.0         14
1         11.0         14
2         19.0          7
3         10.0          7
4         17.0          6

In [6]:
df.select_dtypes(include='float')

   bil_pecahan
0          7.0
1         11.0
2         19.0
3         10.0
4         17.0

In [7]:
df.select_dtypes(include='int')

   bil_bulat
0         14
1         14
2          7
3          7
4          6

## Memilih kolom bertipe data string atau `object`

In [8]:
df.select_dtypes(include='object')

  teks
0    A
1    B
2    C
3    D
4    E

## Memilih kolom bertipe data `datetime`

In [9]:
df.select_dtypes(include='datetime')

                index
0 2023-10-01 00:00:00
1 2023-10-01 01:00:00
2 2023-10-01 02:00:00
3 2023-10-01 03:00:00
4 2023-10-01 04:00:00

## Memilih kolom dengan kombinasi tipe data

In [10]:
df.select_dtypes(include=['number', 'object'])

   bil_pecahan  bil_bulat teks
0          7.0         14    A
1         11.0         14    B
2         19.0          7    C
3         10.0          7    D
4         17.0          6    E