# #30: Akses nilai variabel pada `query()`
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0  14   1   3  17  18
1   5  19   5   9   6
2   8   1  14  16   6
3  15   7   8  12  19
4  17   5   1  18  15

## Akses nilai variabel pada `query()`

In [3]:
df.query('A > 5')

    A  B   C   D   E
0  14  1   3  17  18
2   8  1  14  16   6
3  15  7   8  12  19
4  17  5   1  18  15

In [4]:
df.query('A > 10')

    A  B  C   D   E
0  14  1  3  17  18
3  15  7  8  12  19
4  17  5  1  18  15

In [5]:
rerata = df['A'].mean()
rerata

11.8

In [6]:
df.query('A > @rerata')

    A  B  C   D   E
0  14  1  3  17  18
3  15  7  8  12  19
4  17  5  1  18  15