# #31: Mengenal tipe data ordinal pada Pandas
## Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3

## Persiapan Data Frame

In [2]:
d = {'pelanggan':[11, 12, 13, 14], 
     'kepuasan':['baik', 'cukup', 'buruk', 'cukup']}

df = pd.DataFrame(d)
df

   pelanggan kepuasan
0         11     baik
1         12    cukup
2         13    buruk
3         14    cukup

## Tipe data ordinal pada Pandas

In [3]:
from pandas.api.types import CategoricalDtype

tingkat_kepuasan = CategoricalDtype(['buruk', 'cukup', 'baik', 'sangat baik'], 
                                    ordered=True)

df['kepuasan'] = df['kepuasan'].astype(tingkat_kepuasan)
df

   pelanggan kepuasan
0         11     baik
1         12    cukup
2         13    buruk
3         14    cukup

In [4]:
df = df.sort_values('kepuasan', ascending=True)
df

   pelanggan kepuasan
2         13    buruk
1         12    cukup
3         14    cukup
0         11     baik

In [5]:
df[df['kepuasan'] > 'cukup']

   pelanggan kepuasan
0         11     baik

In [6]:
df[df['kepuasan'] >= 'cukup']

   pelanggan kepuasan
1         12    cukup
3         14    cukup
0         11     baik